name: Lint and Type Check

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        workspace: [ai-voice]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ matrix.workspace }}/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.workspace }}
        env:
          NODE_ENV: test
          
      - name: Run ESLint
        run: npm run lint
        working-directory: ${{ matrix.workspace }}
        continue-on-error: false
        env:
          NODE_ENV: test
        
      - name: TypeScript type check
        run: npm run type-check
        working-directory: ${{ matrix.workspace }}
        env:
          NODE_ENV: test
        
      - name: Check formatting
        run: npx prettier --check "**/*.{ts,tsx,js,jsx,json,md}"
        working-directory: ${{ matrix.workspace }}
        continue-on-error: true
        env:
          NODE_ENV: test
